apiVersion: apps/v1
kind: Deployment #kubernetes resource kind we are creating
metadata:
  name: foodcatalogueapp
  labels:
     app: foodcatalogueapp
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
       app: foodcatalogueapp
  template:
    metadata:
        labels:
          app: foodcatalogueapp
    spec:
      containers:
       - name: foodcatalogueapp
         image: yonatanm/food-catalogue-service:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 9092
          env: # Environment variables supplied to the pod
            - name: SPRING_DATASOURCE_USERNAME  # name of the environment variable
              valueFrom: #Get the value of environment variable from kubernetes
              secretKeyRef:
                 name: secret
                 key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                 secretKeyRef:
                    name: secret
                    key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                 configMapKeyRef:
                    name: configmap
                    key: foodcataloguedb_url
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue-service
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: foodcatalogueapp