apiVersion: apps/v1
kind: Deployment #kubernetes resource kind we are creating
metadata:
  name: userapp
  labels:
      app: userapp
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
       app: userapp
  template:
    metadata:
        labels:
          app: userapp
    spec:
      containers:
       - name: userapp
         image: yonatanm/user-info-service:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 9093
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                 name: secret
                 key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                 secretKeyRef:
                    name: secret
                    key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                 configMapKeyRef:
                    name: configmap
                    key: userdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: userapp